package com.example.weightliftingapp.OneRepMax;

public enum PowerliftingPlatesEnum {
    ZERO_POINT_FIVE_KILOGRAMS,
    ONE_KILOGRAMS,
    ONE_POINT_FIVE_KILOGRAMS,
    TWO_KILOGRAMS,
    TWO_POINT_FIVE_KILOGRAMS,
    FIVE_KILOGRAMS,
    TEN_KILOGRAMS,
    FIFTEEN_KILOGRAMS,
    TWENTY_KILOGRAMS,
    TWENTY_FIVE_KILOGRAMS
}
